spring:
    datasource:
        url: jdbc:mysql://192.168.1.111:3306/tdx_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            initial-size: 5
            max-active: 50
            min-idle: 5
            max-wait: 5000
            time-between-eviction-runs-millis: 1000
            min-evictable-idle-time-millis: 300000
            validation-query: select 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 50
            filters: stat, wall
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
            use-global-data-source-stat: true
    mvc:
        view:
            prefix: classpath:/templates/
            suffix: .html
        static-path-pattern: /static/**
    thymeleaf:
        mode: HTML5
        encoding: UTF-8
        servlet:
            content-type: text/html
        cache: false

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.simplemysqldemo.po
    configuration:
        cache-enabled: false
        map-underscore-to-camel-case: true

logging:
    level:
        com.example.simplemysqldemo: debug